# Define the agents

In [2]:
import random
import math
from numpy.core.shape_base import atleast_2d
import numpy as np
import pandas as pd
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt


import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
import numpy as np


In [3]:
# Import functions in the function file

%run trade_functions3.ipynb


2023


## define encounter matrix

In [4]:
economy_size=1000

In [5]:


# Create a 100x100 matrix filled with 1s
matrix = np.ones((economy_size, economy_size))

# And  Set the diagonal elements to 0
np.fill_diagonal(matrix, 0)


## Define Economy 

In [6]:
agent_a = create_agent()
agent_a['id_list'] = [i for i in range(economy_size)]
#agent_a['parameter']=[[3,3,3] for _ in range(economy_size)]
agent_a['parameter'] = [[3,3,3]] * 1000

agent_a['money']=[1 for _ in range(economy_size)]
agent_a['gooda']=[1 for _ in range(economy_size)]
agent_a['goodb']=[1 for _ in range(economy_size)]



In [7]:
agent_b = create_agent()
agent_b['id_list'] = [i for i in range(economy_size)]
agent_b['parameter']=[[3,3,3] for _ in range(economy_size)]
agent_b['money']=[1 for _ in range(economy_size)]
agent_b['gooda']=[1 for _ in range(economy_size)]
agent_b['goodb']=[1 for _ in range(economy_size)]



In [8]:
# f2: 100 copies of utility_func_cd
f0 = [utility_func_cd] * 1000
f3=[utility_func_t3]*1000
# f1: 50 x utility_func_s + 50 x utility_func_c
fs5c5 = [utility_func_s] * 500 + [utility_func_c] * 500

# f3: 30 x utility_func_s + 30 x utility_func_c + 40 x utility_func_cd
fs3c3cd4 = [utility_func_s] * 300 + [utility_func_c] * 300 + [utility_func_cd] * 400
ft=[utility_func_t1n]*1000

In [9]:
ft32=[utility_func_t32]*1000

In [10]:
agent_c = create_agent()
agent_c['id_list'] = [i for i in range(economy_size)]
agent_c['parameter']=[[2,2,2] for _ in range(economy_size)]
agent_c['money']=[1 for _ in range(economy_size)]
agent_c['gooda']=[1 for _ in range(economy_size)]
agent_c['goodb']=[1 for _ in range(economy_size)]

agent_c['constant']=[1 for _ in range(economy_size)]


#Defne  inhomogeneous economy

In [11]:
def get_value(lst,sum_p,lenx):
    sub_list=lst
    value_list=[ sum_p/x for x in sub_list]
    return np.mean(value_list)
    

In [12]:
def get_v(agent_c,agent_a,gm1,length1,f1,t1,t2):
   
    vga,vgb,vm=tester(agent_c,agent_a,gm1,length1,1,f1,f0,t1,t2)
    
    mvga=get_value(vga,2000,10000)
    mvgb=get_value(vgb,2000,10000)
    mvm=get_value(vm,2000,10000)
    
  
    return mvga,mvgb,mvm
        

In [13]:
import numpy as np

def simulate_grid(gm1_base, g_grid, v_fixed, f1, t1, t2):

    rows = len(g_grid)
    cols = len(g_grid[0])
    
    v1m = []
    v2m = []
    bm = []

    # find index where g3 should go (from one-hot vector)
    g3_idx = int(np.argmax(t2[1]))   # e.g. [0,0,1] -> 2, [0,1,0] -> 1

    for k in range(rows):
        v1l = []
        v2l = []
        bl = []

        for i in range(cols):
            gm1 = gm1_base.copy()

            g3_val, g1_val = g_grid[k][i]

            # g1 always goes to position 0
            gm1[0] = g1_val

            # g3 goes to position determined by t2[1]
            gm1[g3_idx] = g3_val

            g11, g31, m11 = get_v(
                agent_c,
                agent_a,
                gm1,
                v_fixed,
                f1,
                t1,
                t2
            )

            v1l.append(g11)
            v2l.append(g31)
            bl.append(m11)

        v1m.append(v1l)
        v2m.append(v2l)
        bm.append(bl)

        print(f"time {k} v1: {v1m[-1]}, money: {bm[-1]}")

    return v1m, v2m, bm



In [14]:
def tester(agent1,agent2,gm,length,size,f1,f2,t1,t2):
  
  
  mla=[gm[2]]*economy_size
  gala=[gm[0]]*economy_size
  gbla=[gm[1]]*economy_size
  
  parametera=agent2['parameter'].copy()
    
  mlb=agent1['money'].copy()
  galb=agent1['gooda'].copy()
  gblb=agent1['goodb'].copy()
  constant=agent1['constant'].copy()
  parameterb=agent1['parameter'].copy()
  sum_eta=np.sum(agent1['parameter'][2])
  sum_alpha1=np.sum(agent1['parameter'][0])
  sum_alpha2=np.sum(agent1['parameter'][1])
 

  

  ga2_history=[]
  gb2_history=[]
  m2_history=[] 

  for i in range(length[0]):
    
        gala,gbla,mla=t1[0](gala,gbla,mla,parametera,matrix,1,f1,f1)
        
      
        
        galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
        
        
        # test v1,v2 and beta
        gala,gbla,mla,galb,gblb,mlb=t1[1](gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,1,t2[0],f1,f2)
        
        gala,gbla,mla,galb,gblb,mlb=t1[1](gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,1,t2[1],f1,f2)
       
        
       
      
    

    
    
  
    

  for k in range (5):
      size=size*0.5
    
      for j in range(length[1]):
        
        gala,gbla,mla=t1[0](gala,gbla,mla,parametera,matrix,1,f1,f1)
        
      
        
        galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
        
      
        # test v1,v2 and beta
        gala,gbla,mla,galb,gblb,mlb=t1[1](gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,t2[0],f1,f2)
        
        gala,gbla,mla,galb,gblb,mlb=t1[1](gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,t2[1],f1,f2)
    
        
        if k==4:
            ga2_history.append(sum(galb))
            
            gb2_history.append(sum(gblb))
            m2_history.append(sum(mlb))
  

        

  return ga2_history,gb2_history,m2_history

## S5c5

In [27]:
# 构造 gm 网格（10x10 的 g3-g1 组合）
#g_grid = [[(1.201 - 0.1 * k, 1.201 - 0.1 * i) for i in range(10)] for k in range(10)]
g_grid = [[(1 + 0.1 * k, 1 + 0.05 * i) for i in range(10)] for k in range(10)]

# 调用
v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=fs5c5,
    t1=[intra_trade,test_trade],
    t2=[[1,0,0],[0,1,0]]
)


time 0 v1: [2.002693858898391, 1.908861813865586, 1.8165119998658208, 1.7324437530422427, 1.6789209274431036, 1.626136120606776, 1.5589042914817146, 1.4963652798340656, 1.4429578187838248, 1.4086805556095117], money: [2.0, 2.0, 2.0, 1.9999999999999996, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
time 1 v1: [1.9952982828040502, 1.8968112564375221, 1.8191088641952755, 1.7589653248501276, 1.675142184551185, 1.6173767953051188, 1.5395135263062674, 1.4898506039045556, 1.449861244145362, 1.3919042119893268], money: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.9999999999999996, 2.0]
time 2 v1: [1.990166218612681, 1.8935340183072527, 1.8168243196481328, 1.7515061706316155, 1.6781093051530076, 1.601034515495618, 1.54983820713173, 1.4697260002150698, 1.4412220133363574, 1.388927866633196], money: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.9999999999999996]
time 3 v1: [1.9691690232425942, 1.875305054391118, 1.808111754309024, 1.7108839372801212, 1.6594409795322775, 1.6144686559214603, 1.536102438794295, 1.4

In [28]:
import numpy as np

def round_matrix_5(matrix):
    return np.round(matrix, 5)


In [29]:
print(np.round(v1m,5))

[[2.00269 1.90886 1.81651 1.73244 1.67892 1.62614 1.5589  1.49637 1.44296
  1.40868]
 [1.9953  1.89681 1.81911 1.75897 1.67514 1.61738 1.53951 1.48985 1.44986
  1.3919 ]
 [1.99017 1.89353 1.81682 1.75151 1.67811 1.60103 1.54984 1.46973 1.44122
  1.38893]
 [1.96917 1.87531 1.80811 1.71088 1.65944 1.61447 1.5361  1.46186 1.44832
  1.39854]
 [1.96871 1.88502 1.80311 1.73609 1.63474 1.57867 1.52608 1.47625 1.43288
  1.3743 ]
 [1.97001 1.8816  1.79452 1.72035 1.66129 1.59928 1.52711 1.46428 1.43933
  1.36788]
 [1.9561  1.85887 1.80553 1.72522 1.64741 1.58719 1.53203 1.47748 1.42702
  1.36688]
 [1.95619 1.85432 1.79727 1.70402 1.63821 1.58798 1.52378 1.45693 1.41729
  1.37431]
 [1.95464 1.88351 1.79302 1.70632 1.6351  1.60069 1.51522 1.44674 1.41233
  1.36331]
 [1.96554 1.87254 1.79386 1.70707 1.65644 1.56574 1.51235 1.47103 1.40854
  1.36248]]


In [30]:
print(np.round(v2m,5))

[[2.00113 1.97735 1.98915 2.00331 1.98191 1.969   1.99473 1.95979 1.987
  1.97743]
 [1.82371 1.8509  1.80164 1.80811 1.8108  1.80096 1.81028 1.796   1.80373
  1.80042]
 [1.68511 1.68362 1.66494 1.66284 1.67167 1.65949 1.66098 1.64175 1.66311
  1.65047]
 [1.55615 1.53793 1.54038 1.54253 1.54783 1.54432 1.55414 1.55106 1.53064
  1.53611]
 [1.44969 1.44215 1.44175 1.44571 1.41793 1.43795 1.41825 1.42234 1.43653
  1.42737]
 [1.34705 1.3524  1.35956 1.35384 1.34402 1.35267 1.3416  1.34233 1.34722
  1.34313]
 [1.28172 1.26612 1.26661 1.26992 1.26841 1.25661 1.26933 1.25648 1.25719
  1.25176]
 [1.19713 1.19627 1.20089 1.19042 1.1822  1.19056 1.20301 1.18566 1.1926
  1.1849 ]
 [1.14041 1.13899 1.1289  1.13424 1.125   1.12849 1.13157 1.12225 1.12249
  1.11944]
 [1.06762 1.07963 1.07562 1.07969 1.07282 1.07429 1.06282 1.06144 1.06616
  1.06344]]


In [31]:
print(np.round(bm,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [32]:
## decrease to 300

In [15]:

#g_grid = [[(1.3 - 0.1 * k, 1.3 - 0.1 * i) for i in range(10)] for k in range(10)]
g_grid = [[(1 + 0.1 * k, 1 + 0.05 * i) for i in range(10)] for k in range(10)]


v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=fs3c3cd4,
    t1=[intra_trade,test_trade],
    t2=[[1,0,0],[0,1,0]]
)

time 0 v1: [2.394716280355489, 2.2901044820688194, 2.183882515188798, 2.079268958909262, 2.00183735140623, 1.941147800059825, 1.8648427284612066, 1.7917071745357371, 1.7135524142961076, 1.6732710180075934], money: [2.0, 2.0, 2.0000000000000004, 2.0, 2.0, 2.0, 2.0, 1.9999999999999996, 2.0, 2.0]
time 1 v1: [2.390710539167239, 2.2670503541406566, 2.1791443105670085, 2.082805457755969, 2.0104631809874736, 1.9353998211517478, 1.857530220983708, 1.78283984111, 1.7340216570361797, 1.653507822491346], money: [1.9999999999999996, 2.0, 2.0, 1.9999999999999996, 2.0, 2.0000000000000004, 2.0, 1.9999999999999996, 1.9999999999999996, 2.0]
time 2 v1: [2.3755983271321583, 2.3100241474503793, 2.1704661447777966, 2.0762957325460407, 1.9944870384110243, 1.9322610099051962, 1.8599883964120811, 1.7994793088175174, 1.7199581335467793, 1.66595944351996], money: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0000000000000004, 2.0, 2.0]
time 3 v1: [2.3668888430465342, 2.284430874155813, 2.1623624793302567, 2.08199715053

In [16]:
print(np.round(v1m,5))

[[2.39472 2.2901  2.18388 2.07927 2.00184 1.94115 1.86484 1.79171 1.71355
  1.67327]
 [2.39071 2.26705 2.17914 2.08281 2.01046 1.9354  1.85753 1.78284 1.73402
  1.65351]
 [2.3756  2.31002 2.17047 2.0763  1.99449 1.93226 1.85999 1.79948 1.71996
  1.66596]
 [2.36689 2.28443 2.16236 2.082   1.98655 1.92334 1.85088 1.77085 1.72547
  1.66112]
 [2.42388 2.26691 2.16244 2.08417 2.01901 1.90944 1.8431  1.77102 1.72034
  1.66486]
 [2.39631 2.27747 2.16288 2.07537 1.99465 1.89377 1.84419 1.77037 1.72083
  1.65542]
 [2.36816 2.25094 2.18916 2.06893 1.99928 1.89914 1.83151 1.776   1.71115
  1.64695]
 [2.36096 2.25565 2.16949 2.07034 2.00717 1.92397 1.8295  1.75818 1.72448
  1.65204]
 [2.36041 2.27107 2.17268 2.07692 1.99481 1.91092 1.85377 1.76743 1.70061
  1.64325]
 [2.38051 2.26731 2.14862 2.07993 1.97811 1.89816 1.82692 1.78755 1.71067
  1.64277]]


In [17]:
print(np.round(v2m,5))

[[2.39585 2.38454 2.39888 2.4106  2.37247 2.40138 2.38245 2.39072 2.39011
  2.40621]
 [2.18786 2.1717  2.16786 2.16092 2.18514 2.16925 2.19454 2.1655  2.16102
  2.18195]
 [1.98957 1.99832 1.9952  1.99202 1.99937 1.99191 2.00681 1.98598 1.99291
  2.00157]
 [1.85691 1.87272 1.84747 1.86439 1.84714 1.85713 1.85314 1.84731 1.83671
  1.84898]
 [1.72909 1.69672 1.70448 1.72362 1.72408 1.72507 1.72851 1.70502 1.70112
  1.71932]
 [1.6126  1.60664 1.60426 1.61347 1.6096  1.60663 1.60011 1.61536 1.61618
  1.60611]
 [1.52291 1.49803 1.50043 1.49951 1.51271 1.50275 1.52333 1.50866 1.50944
  1.51315]
 [1.42351 1.42856 1.41297 1.42055 1.41808 1.41403 1.42089 1.40451 1.41051
  1.4217 ]
 [1.3509  1.33988 1.34289 1.33194 1.33576 1.34115 1.33667 1.33068 1.32708
  1.33823]
 [1.28595 1.28731 1.27605 1.27725 1.27834 1.26715 1.2622  1.27757 1.27617
  1.27544]]


In [18]:
print(np.round(bm,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


## neighbour

In [76]:

#g_grid = [[(1.3 - 0.1 * k, 1.3 - 0.1 * i) for i in range(10)] for k in range(10)]
g_grid = [[(1 + 0.1 * k, 1 + 0.1 * i) for i in range(10)] for k in range(10)]


v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=f3,
    t1=[intra_tradet3n,test_tradet3n],
    t2=[[1,0,0],[0,0,1]]
)

time 0 v1: [3.9780148764594196, 3.7113498300425345, 3.4905671453852074, 3.2958031165804735, 3.1250229757648578, 2.980176989475407, 2.8418883755841935, 2.764034321478699, 2.6471115768081614, 2.5601744374644624], money: [2.997857982229341, 2.97795370064152, 3.0012209647270724, 3.0094175751289853, 2.9860598877535356, 3.0187039519906502, 3.0124581091666705, 2.9961151977583564, 2.9786007202755207, 2.993325183346825]
time 1 v1: [3.9653632491034188, 3.740247802632325, 3.5059461119832087, 3.2992486648428674, 3.131383655511227, 3.006387641773136, 2.8843330748623686, 2.7433268936782924, 2.64865122699045, 2.5897411808672386], money: [2.7227334850702647, 2.738167925081217, 2.7341094935132153, 2.719575493887667, 2.7252759789813363, 2.715290006116245, 2.731467609724921, 2.736647493059712, 2.7156724254047178, 2.696803103343167]
time 2 v1: [3.981384981877087, 3.7150190621249743, 3.4958272615743384, 3.307623475826421, 3.130844050892316, 2.977677448305451, 2.86533514885721, 2.748545807370537, 2.65081271

KeyboardInterrupt: 

In [ ]:
print(np.round(v1m,5))

In [ ]:
print(np.round(v2m,5))

In [ ]:
print(np.round(bm,5))

In [15]:

#g_grid = [[(1.3 - 0.1 * k, 1.3 - 0.1 * i) for i in range(10)] for k in range(10)]
g_grid = [[(1 + 0.1 * k, 1 + 0.1 * i) for i in range(10)] for k in range(10)]


v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=ft32,
    t1=[intra_tradet3n,test_tradet3n],
    t2=[[1,0,0],[0,0,1]]
)

time 0 v1: [3.7217015383855694, 3.3967297092023596, 3.149330073714308, 2.9064183286077214, 2.7081124669817487, 2.554679985375765, 2.38811608105146, 2.249411781452531, 2.12828574190278, 2.0229944467654053], money: [3.0310441796527803, 3.0198692833807423, 3.0086847348186088, 3.0016272708240566, 2.9849197681011663, 2.9865780966881146, 3.0047903095882664, 3.0045969411380096, 2.980399760775338, 2.981913359549929]
time 1 v1: [3.7142361416973704, 3.3635462814681603, 3.165708850075056, 2.9390023052097285, 2.7104367843560535, 2.560064616376258, 2.377202851331416, 2.2391845195057853, 2.132731473394757, 2.0259197924889976], money: [2.7288834401359097, 2.713850548136985, 2.709471306274075, 2.717714520904008, 2.7328574289343175, 2.7541488893426753, 2.7504717848520124, 2.758793068011863, 2.7309956202800247, 2.726017015537225]
time 2 v1: [3.7206968788484795, 3.395947786926835, 3.1411791207333986, 2.906636951683897, 2.693141094539888, 2.5187386975624855, 2.3682000970270516, 2.2458670119435427, 2.12215

In [16]:
print(np.round(v1m,5))

[[3.7217  3.39673 3.14933 2.90642 2.70811 2.55468 2.38812 2.24941 2.12829
  2.02299]
 [3.71424 3.36355 3.16571 2.939   2.71044 2.56006 2.3772  2.23918 2.13273
  2.02592]
 [3.7207  3.39595 3.14118 2.90664 2.69314 2.51874 2.3682  2.24587 2.12215
  2.01482]
 [3.6879  3.38037 3.11906 2.91803 2.70184 2.5461  2.36963 2.27775 2.13187
  2.02193]
 [3.68819 3.38265 3.15563 2.89744 2.70957 2.55366 2.39794 2.25282 2.13079
  2.0324 ]
 [3.74562 3.39026 3.12787 2.92951 2.71573 2.52835 2.37244 2.25238 2.12227
  2.01989]
 [3.71099 3.38425 3.14552 2.89878 2.70798 2.53635 2.40246 2.24217 2.12422
  2.01735]
 [3.70905 3.40663 3.13671 2.93208 2.71781 2.54056 2.40702 2.23915 2.11345
  2.01779]
 [3.69724 3.4023  3.14361 2.91517 2.71019 2.54592 2.37084 2.27319 2.11099
  2.00569]
 [3.72213 3.39913 3.13494 2.92421 2.72073 2.54399 2.36657 2.23309 2.10883
  2.02018]]


In [17]:
print(np.round(v2m,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [18]:
print(np.round(bm,5))

[[3.03104 3.01987 3.00868 3.00163 2.98492 2.98658 3.00479 3.0046  2.9804
  2.98191]
 [2.72888 2.71385 2.70947 2.71771 2.73286 2.75415 2.75047 2.75879 2.731
  2.72602]
 [2.48947 2.49657 2.51659 2.49587 2.48381 2.4801  2.50075 2.49627 2.49591
  2.49131]
 [2.32422 2.30588 2.30501 2.3061  2.319   2.31131 2.28323 2.31212 2.28178
  2.30933]
 [2.13068 2.14724 2.1458  2.11365 2.14516 2.12927 2.1428  2.16074 2.1512
  2.14446]
 [2.0111  1.9949  1.99255 1.98889 2.00123 2.00173 2.00182 1.99475 1.99838
  2.01212]
 [1.86819 1.87816 1.8756  1.8781  1.87918 1.86827 1.87571 1.89583 1.88955
  1.87444]
 [1.78441 1.78754 1.76318 1.78532 1.76722 1.7561  1.76779 1.7688  1.7551
  1.75741]
 [1.67297 1.68487 1.66235 1.6477  1.66972 1.65756 1.66317 1.65336 1.67964
  1.66468]
 [1.56735 1.58712 1.57968 1.58402 1.57541 1.5804  1.57303 1.57137 1.58164
  1.57746]]


## edge

In [20]:
ft2=[utility_func_t32]*1000
ft22=[utility_func_t32]*1000

In [21]:
v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=f0,
    t1=[intra_tradet2,test_tradet2],
    t2=[[1,0,0],[0,0,1]]
)

time 0 v1: [2.9939384501862647, 2.7105104096819352, 2.5148780702733617, 2.3023460403668556, 2.1340236809988418, 1.996469149495541, 1.883249914891048, 1.7701082416209035, 1.660154626640851, 1.5830021728736516], money: [3.010633707964969, 3.0145119412555275, 3.0020104289250833, 2.988101834035133, 2.9611426191175436, 2.995412152552422, 2.992219594239964, 3.0272729038535307, 3.0172475284152793, 3.014234660350114]
time 1 v1: [3.0094452195333776, 2.7343635243279953, 2.5063481461266854, 2.290862392183249, 2.1423388908047136, 2.0249611940530463, 1.8725173552187857, 1.7381027428798141, 1.6688468234979372, 1.560329932967487], money: [2.7372792706412685, 2.7210786027299676, 2.696550148348957, 2.755685340690103, 2.7467886681841773, 2.7482158187356327, 2.7085832737417235, 2.729535737186108, 2.76473751766958, 2.7271735912887087]
time 2 v1: [2.9788274115615243, 2.7236886262377675, 2.5080644949783424, 2.2936000908458247, 2.1345464467473727, 2.0063005944780703, 1.8622920485788688, 1.7712483486864659, 1

In [22]:
print(np.round(v1m,5))

[[2.99394 2.71051 2.51488 2.30235 2.13402 1.99647 1.88325 1.77011 1.66015
  1.583  ]
 [3.00945 2.73436 2.50635 2.29086 2.14234 2.02496 1.87252 1.7381  1.66885
  1.56033]
 [2.97883 2.72369 2.50806 2.2936  2.13455 2.0063  1.86229 1.77125 1.68043
  1.58316]
 [2.98329 2.74948 2.51645 2.32376 2.14631 2.00352 1.86934 1.75503 1.66948
  1.58624]
 [2.98654 2.70893 2.47965 2.31474 2.14604 1.99575 1.88091 1.74151 1.69315
  1.59317]
 [3.0081  2.72437 2.51529 2.28314 2.13853 2.00427 1.87344 1.78165 1.67423
  1.56876]
 [2.98547 2.71486 2.50892 2.31258 2.15796 1.99868 1.8795  1.75743 1.67375
  1.58412]
 [3.01431 2.73173 2.5045  2.30795 2.16265 2.00254 1.88358 1.76975 1.67786
  1.58056]
 [3.02225 2.71894 2.5     2.32191 2.15842 2.03847 1.85291 1.77908 1.6735
  1.57466]
 [3.01649 2.73799 2.49263 2.30118 2.1485  1.98336 1.8843  1.7694  1.64136
  1.56181]]


In [23]:
print(np.round(v2m,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [24]:
print(np.round(bm,5))

[[3.01063 3.01451 3.00201 2.9881  2.96114 2.99541 2.99222 3.02727 3.01725
  3.01423]
 [2.73728 2.72108 2.69655 2.75569 2.74679 2.74822 2.70858 2.72954 2.76474
  2.72717]
 [2.48592 2.49463 2.48514 2.51305 2.49769 2.51902 2.48815 2.48612 2.50215
  2.47839]
 [2.34252 2.30953 2.31792 2.27606 2.28961 2.318   2.31486 2.28543 2.29322
  2.34366]
 [2.13184 2.15648 2.14373 2.15601 2.15387 2.12892 2.12662 2.11986 2.11977
  2.14501]
 [1.99314 1.97252 2.00937 1.97529 1.99726 1.99972 1.99851 1.99075 1.98562
  2.00126]
 [1.86392 1.90701 1.88224 1.86879 1.88724 1.85758 1.88573 1.85551 1.89661
  1.86039]
 [1.75493 1.75311 1.7752  1.75324 1.7883  1.76824 1.74784 1.76049 1.7582
  1.76439]
 [1.67173 1.66188 1.6773  1.66773 1.66937 1.67756 1.67378 1.68172 1.66418
  1.65785]
 [1.57541 1.57465 1.58412 1.58009 1.5778  1.57207 1.58558 1.57299 1.58739
  1.58576]]


## edge 2

In [25]:
agent_a = create_agent()
agent_a['id_list'] = [i for i in range(economy_size)]
#agent_a['parameter']=[[3,3,3，】] for _ in range(economy_size)]
economy_size = 1000

agent_a['parameter'] = [[3, 3, 3, [0.9, 1.1]] for _ in range(economy_size)]


agent_a['money']=[1 for _ in range(economy_size)]
agent_a['gooda']=[1 for _ in range(economy_size)]
agent_a['goodb']=[1 for _ in range(economy_size)]

In [27]:
agent_a['parameter'][2]

[3, 3, 3, [0.9, 1.1]]

In [43]:
v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=f0,
    t1=[intra_tradet2n,test_tradet2n],
    t2=[[1,0,0],[0,0,1]]
)

time 0 v1: [1.8491402461446123, 1.6880813998708124, 1.5539946043561417, 1.4311372317651299, 1.3254127736558554, 1.2295730086254748, 1.1530500502330623, 1.1003194395274476, 1.0339384908765068, 0.9729076286219701], money: [1.8550390605752292, 1.8496629886806621, 1.86964005547639, 1.8390790156285541, 1.8500910678189089, 1.8511766450757077, 1.8573864317315016, 1.8528079185823778, 1.8402576767100531, 1.8668805493923464]
time 1 v1: [1.859592450512321, 1.6851487263375886, 1.5491680913356933, 1.4244448099670712, 1.329199115621216, 1.2393463070249269, 1.1607102550953365, 1.0970460914548483, 1.0321426634135233, 0.9838776874625482], money: [1.6944479154554353, 1.6836038754141083, 1.7048854241018634, 1.6838450345025238, 1.697898474106255, 1.6884218729040903, 1.6768434003375507, 1.6928376879394749, 1.6653892317968109, 1.694804585889059]
time 2 v1: [1.8518647217731294, 1.7009455872237915, 1.5539460898870592, 1.4280369632132315, 1.3375003023150487, 1.2341535159796748, 1.162182510827346, 1.08843569299

In [44]:
print(np.round(v1m,5))

[[1.84914 1.68808 1.55399 1.43114 1.32541 1.22957 1.15305 1.10032 1.03394
  0.97291]
 [1.85959 1.68515 1.54917 1.42444 1.3292  1.23935 1.16071 1.09705 1.03214
  0.98388]
 [1.85186 1.70095 1.55395 1.42804 1.3375  1.23415 1.16218 1.08844 1.02615
  0.97185]
 [1.86833 1.68913 1.5445  1.42507 1.32986 1.23259 1.15681 1.09966 1.02688
  0.98041]
 [1.84497 1.70819 1.54541 1.4388  1.32092 1.23517 1.16559 1.09598 1.02412
  0.97458]
 [1.86584 1.68734 1.54149 1.42476 1.31677 1.22993 1.15611 1.08858 1.03369
  0.98019]
 [1.85672 1.67197 1.54466 1.43354 1.34504 1.22993 1.16663 1.09467 1.03395
  0.97548]
 [1.8691  1.67898 1.54547 1.42859 1.32542 1.23725 1.15599 1.09228 1.03432
  0.97664]
 [1.89213 1.70369 1.55933 1.4385  1.3294  1.24526 1.16905 1.09114 1.02694
  0.97068]
 [1.85809 1.65525 1.54023 1.41226 1.32112 1.24189 1.17216 1.09108 1.03903
  0.98492]]


In [45]:
print(np.round(v2m,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [46]:
print(np.round(bm,5))

[[1.85504 1.84966 1.86964 1.83908 1.85009 1.85118 1.85739 1.85281 1.84026
  1.86688]
 [1.69445 1.6836  1.70489 1.68385 1.6979  1.68842 1.67684 1.69284 1.66539
  1.6948 ]
 [1.55969 1.53857 1.55062 1.52747 1.53992 1.54846 1.52908 1.56201 1.54971
  1.53645]
 [1.4144  1.42627 1.42458 1.41957 1.42814 1.43714 1.42672 1.44152 1.42283
  1.4322 ]
 [1.33457 1.30737 1.32245 1.32402 1.32144 1.31966 1.32304 1.32767 1.31208
  1.32015]
 [1.235   1.24354 1.23802 1.2402  1.2291  1.22707 1.23184 1.24082 1.21983
  1.23898]
 [1.15955 1.15822 1.16621 1.16473 1.16967 1.15799 1.15382 1.16404 1.16345
  1.1548 ]
 [1.0955  1.09136 1.09469 1.09295 1.09936 1.09933 1.0828  1.09373 1.08937
  1.09055]
 [1.03005 1.02412 1.02956 1.02768 1.03906 1.03703 1.03528 1.02751 1.03151
  1.03003]
 [0.97775 0.97683 0.97255 0.98287 0.97704 0.98198 0.9715  0.97921 0.96525
  0.97321]]


## edge 3

In [51]:
intervals = [
    [0.5, 1.5],
    [0.6, 1.4],
    [0.7, 1.3],
    [0.8, 1.2],
    [0.9, 1.1]
]

group_size = 200

for g, interval in enumerate(intervals):
    start = g * group_size
    end   = (g + 1) * group_size
    for i in range(start, end):
        agent_a['parameter'][i][-1] = interval


In [52]:
v1m,v2m, bm = simulate_grid(
    gm1_base=[1,1,1],
    g_grid=g_grid,
    v_fixed=[20000, 20000],
    f1=f0,
    t1=[intra_tradet2n,test_tradet2n],
    t2=[[1,0,0],[0,0,1]]
)

time 0 v1: [1.8537336897219088, 1.6888566747581755, 1.5492873916967962, 1.4131292930646349, 1.3335336233531454, 1.235832147566951, 1.152063374684019, 1.089654616288177, 1.0302713082217327, 0.9828241231412352], money: [1.8426823238739172, 1.8683703521394932, 1.8557390617659464, 1.8558159295497538, 1.8552493664260736, 1.846394924050043, 1.857479967485994, 1.8456584841196126, 1.8539059841083254, 1.8528519984293896]
time 1 v1: [1.8617629943942593, 1.680288115907777, 1.5358467219587288, 1.43356044494703, 1.3410124149907685, 1.2378838831426793, 1.1563216261448, 1.099565570521256, 1.0337267839081221, 0.9793444684164615], money: [1.6668184529423284, 1.6802357617933834, 1.685266287299116, 1.6783337847334925, 1.675869759748317, 1.6884955351391706, 1.6775237509515246, 1.6838045846617828, 1.6990389967224178, 1.6865961437382953]
time 2 v1: [1.8379973311561177, 1.6919032772884737, 1.5506610664708202, 1.4393294785513104, 1.3359405459074543, 1.2394141205851328, 1.1585642992706027, 1.0994641562219083, 

In [53]:
print(np.round(v1m,5))

[[1.85373 1.68886 1.54929 1.41313 1.33353 1.23583 1.15206 1.08965 1.03027
  0.98282]
 [1.86176 1.68029 1.53585 1.43356 1.34101 1.23788 1.15632 1.09957 1.03373
  0.97934]
 [1.838   1.6919  1.55066 1.43933 1.33594 1.23941 1.15856 1.09946 1.04099
  0.98399]
 [1.84503 1.69163 1.55161 1.42998 1.32793 1.2473  1.15508 1.08734 1.02894
  0.98004]
 [1.87422 1.66783 1.55701 1.42587 1.33801 1.22617 1.16878 1.09168 1.02312
  0.98608]
 [1.84858 1.71221 1.55707 1.44658 1.33935 1.23418 1.159   1.09031 1.02849
  0.98008]
 [1.86475 1.70555 1.55784 1.42692 1.3221  1.22527 1.17607 1.1013  1.02596
  0.98205]
 [1.85127 1.68915 1.5559  1.42224 1.34417 1.23861 1.14945 1.08035 1.03348
  0.98011]
 [1.85789 1.67311 1.54392 1.41628 1.33357 1.24331 1.1616  1.09672 1.03828
  0.98284]
 [1.84863 1.69594 1.54186 1.42308 1.31849 1.23158 1.16041 1.09422 1.02859
  0.97291]]


In [54]:
print(np.round(v2m,5))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [55]:
print(np.round(bm,5))

[[1.84268 1.86837 1.85574 1.85582 1.85525 1.84639 1.85748 1.84566 1.85391
  1.85285]
 [1.66682 1.68024 1.68527 1.67833 1.67587 1.6885  1.67752 1.6838  1.69904
  1.6866 ]
 [1.54703 1.55173 1.54494 1.5363  1.54746 1.53411 1.53819 1.54585 1.54016
  1.55767]
 [1.42505 1.42847 1.42326 1.43208 1.44668 1.42408 1.43068 1.4255  1.42122
  1.43695]
 [1.32418 1.32341 1.32469 1.32518 1.33802 1.33643 1.32309 1.3357  1.32848
  1.33148]
 [1.22373 1.22945 1.2326  1.23996 1.23635 1.23695 1.22477 1.24721 1.24521
  1.2418 ]
 [1.15617 1.16329 1.15632 1.16012 1.14807 1.15471 1.17209 1.17287 1.158
  1.17168]
 [1.07701 1.08934 1.09987 1.08435 1.08446 1.08463 1.09876 1.0936  1.10772
  1.1009 ]
 [1.02546 1.03472 1.02458 1.03537 1.02865 1.01887 1.03261 1.03415 1.03438
  1.03335]
 [0.98202 0.97263 0.97397 0.98466 0.97103 0.97958 0.98436 0.97112 0.97856
  0.96627]]
